### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by AnotherSimon** [openvar/rest_variantValidator#29]
Submitting the following variant thought me something

`http://0.0.0.0:8000/variantvalidator/hg19/chr2:48010558:CTC:GAG/all`

Response was:

`{'flag': ' Major error', 'validation_error': 'A major validation error has occurred. Admin have been made aware of the issue'}`

Note the redundant space before "Major error". 

Admin been made aware, does this refer to the public instance only or even when I am running locally?

FYI:
```python
>>> variantvalidator_version
'1.0.4.dev17+gd16b9ef'
>>> variantvalidator_hgvs_version
'1.2.5.vv1'
```

**Comment by PeteCausey-Freeman** [comment]
Thanks, I'll take a look at the cause.

The errors also need updating. When the tool was linked to our internal APIs all errors were automatically emailed back to us for debugging. This doesn't work in docker. Thanks for letting me know, I will update the error messages as well

**Comment by PeteCausey-Freeman** [comment]
Major error means that processing has failed. It will be a bug.

**Comment by PeteCausey-Freeman** [comment]
Hi @AnotherSimon 

Sorry for the delay on this. The issue no longer seems to be a problem. It is likely you are running an old version of the API. 

Try re-building from the develop branch

```bash
$ git fetch
$ git checkout develop
$ git pull
```

Then follow the docker installations
