### ISSUE TITLE
Additional amino acid level outputs needed

### ISSUE THREAD

**Issue by leicray** [openvar/rest_variantValidator#32]
The API produces amino acid level output such as:

    "hgvs_predicted_protein_consequence": {
      "slr": "NP_000080.2:p.(G1018D)",
      "tlr": "NP_000080.2(LRG_2p1):p.(Gly1018Asp)"
    }

The "tlr" output includes the LRG transcript designation, if it exists, but some users might not want it "messing up" an otherwise simple output that would read  "NP_000080.2:p.(Gly1018Asp)". At present, the only way of avoiding having the LRG transcript designation in the output is to select "slr" for the single-letter code version.

I propose two additional outputs such that we get:

    "hgvs_predicted_protein_consequence": {
      "slr": "NP_000080.2:p.(G1018D)",
      "id1": "NP_000080.2(LRG_2p1):p.(G1018D)",
      "id2": "NP_000080.2:p.(Gly1018Asp)"
      "tlr": "NP_000080.2(LRG_2p1):p.(Gly1018Asp)"
    }

**Comment by PeteCausey-Freeman** [comment]
Agreed
I've been thinking about this one as well and how to handle it

I prefer
```json
"hgvs_predicted_protein_consequence": {
  "slr": "NP_000080.2:p.(G1018D)",
  "lrg_slr": "LRG_2p1:p.(G1018D)",
  "lrg_tlr": "LRG_2p1:p.(Gly1018Asp)"
  "tlr": "NP_000080.2(LRG_2p1):p.(Gly1018Asp)"
}

**Comment by PeteCausey-Freeman** [comment]
We will also expand the tables in interactive to reflect this

**Comment by ifokkema** [comment]
> I prefer
> 
> ```json
> "hgvs_predicted_protein_consequence": {
>   "slr": "NP_000080.2:p.(G1018D)",
>   "lrg_slr": "LRG_2p1:p.(G1018D)",
>   "lrg_tlr": "LRG_2p1:p.(Gly1018Asp)",
>   "tlr": "NP_000080.2:p.(Gly1018Asp)"
> }
> ```

This looks better, I agree :wink:    (if I may :laughing: )

I would change the output of the `tlr` field, but I'm not sure if I would need to modify code (I'm already removing the LRG part). It may break existing implementations of the API.

Soooo, just to annoy you guys a little bit :laughing:  I'm just going to drop this here: https://github.com/openvar/variantValidator/issues/128

**Comment by leicray** [comment]
Now I'm really confused. You must have gone back and edited your preferred output format as the alert that was emailed to me said:

`"tlr": "NP_000080.2(LRG_2p1):p.(Gly1018Asp)"`

I agree that we ought to avoid having two (or more?) reference sequence identifiers ahead of a variant description. Otherwise, it could get very messy once we can handle Ensembl transcripts. These chould perhaps be displayed as "ens_slr" and "ens_tlr",

**Comment by PeteCausey-Freeman** [comment]
You may comment indeed.

I was actually going to ask you too. 

To be honest in terms of https://github.com/openvar/variantValidator/issues/128 I'm really not sure how easy this is going to be in the short-term. Really need to look at our infrastructure. 

Currently the API is not widely used and I have direct contact with the primary users who ought to be using it! I also want those who I don't know about to contact us. So, I'm thinking that the first build of the API which is fully integrated and tested in LOVD and has the new UTA hooked up will be API version 1. We will version the API from then on. The next change is going to be huge and I do not intend to continue to support the previous builds.

**Comment by PeteCausey-Freeman** [comment]
I do agree though

**Comment by PeteCausey-Freeman** [comment]
Hi Raymond,

I did edit yes.

The scenario you propose is impossible because predictions are made in the context of a selected transcript, so RefSeq and Ensembl would never exist in the same output json

**Comment by leicray** [comment]
If a heavily revised version of the API will be version 1, and backwards compatibility can be forgotten about, the six transcript-based outputs should be:

```
"refseq_slr"
"refseq_tlr"
"lrg_slr"
"lrg_tlr"
"ens_slr"
"ens_tlr"
```

**Comment by PeteCausey-Freeman** [comment]
"refseq_slr"
"refseq_tlr"
"lrg_slr"
"lrg_tlr"
"ens_slr"
"ens_tlr"

Hi @leicray, I see what you are saying, but this suggestion unnecessary. we need 4 only outputs to fit all scenarios

```json
"hgvs_predicted_protein_consequence": {
  "slr": "NP_000080.2:p.(G1018D)",
  "lrg_slr": "LRG_2p1:p.(G1018D)",
  "lrg_tlr": "LRG_2p1:p.(Gly1018Asp)",
  "tlr": "NP_000080.2:p.(Gly1018Asp)"
}

What you have suggested makes no practical sense and will break existing installations. Changes to the json structure are deliberately subtle. We try to keep existing keywords deliberately. Also ens and refseq CANNOT exist in the same output so there is no need for 6 terms

**Comment by PeteCausey-Freeman** [comment]
Hi @leicray. For testing do you by any chance have the c. or g. description that produces this output?

**Comment by ifokkema** [comment]
> To be honest in terms of [openvar/variantValidator#128](https://github.com/openvar/variantValidator/issues/128) I'm really not sure how easy this is going to be in the short-term. Really need to look at our infrastructure.

There are many ways to actually implement versioning, including making copies of older code and keeping it running somewhere else, or making aliases of internal methods and just accepting the requested version as an additional argument to find out which alias you should run. What will work for you heavily depends on your internal structure indeed, of which I, unfortunately, don't know much.


> Currently the API is not widely used and I have direct contact with the primary users who ought to be using it! I also want those who I don't know about to contact us.

Oh, that's excellent! That does give you a lot of freedom.


> So, I'm thinking that the first build of the API which is fully integrated and tested in LOVD and has the new UTA hooked up will be API version 1. We will version the API from then on. The next change is going to be huge and I do not intend to continue to support the previous builds.

Cool! :+1: 


> Also ens and refseq CANNOT exist in the same output so there is no need for 6 terms

The only exception here is MANE transcripts. In principle, I agree that `slr` and `tlr` just contain the annotation related to the transcript (NP for NMs and ENSP for ENST) and are sufficient. If we do want to know however which transcripts relate to each other, how could we include that information? I suppose we can't merge them in the API so keeping `slr` and `tlr` like this and then adding an alias perhaps? :thinking: 
I guess I'm just overcomplicating things, never mind :laughing:

**Comment by leicray** [comment]
The outputs were generated beginning with NM_000089.3:c.3053G>A

The API is now being used for the BOOSTB4 project patient database the input above is a variant found in one of the patients.

**Comment by PeteCausey-Freeman** [comment]
Not at all.

You agree at versioning at the next major release. Practically speaking, without more support this is gonna have to happen :)

As for MANE, this is already sorted. We will give the MANE ID in the output, we will never give an Ens and RefSeq in the same nested dictionary. MANE transcripts have 2 separate IDs and ens and and NM_ . I think MANE will remain an annotation nor a reference sequence ID like LRG

**Comment by PeteCausey-Freeman** [comment]
Thanks @leicray

**Comment by ifokkema** [comment]
Cool, Pete!! :+1:

**Comment by PeteCausey-Freeman** [comment]
Moved to VV issues
https://github.com/openvar/variantValidator/issues/230
