### ISSUE TITLE
New endpoint get_metadata

### ISSUE THREAD

**Issue by beboche** [openvar/rest_variantValidator#47]
Would be nice to create a new endpoint to get the database version in order to know whether or not the database has been updated with new transcript IDs, etc

**Comment by ifokkema** [comment]
Perhaps it's most efficient to extend the existing `hello` method with the standard `metadata` array that the other services output?

```json
{
  "metadata": {
    "seqrepo_db": "2018-08-21",
    "uta_schema": "uta_20180821",
    "variantvalidator_hgvs_version": "1.2.5.vv1",
    "variantvalidator_version": "1.0.4.dev116+g0b957e0"
  }
}
```

**Comment by PeteCausey-Freeman** [comment]
Fantastic idea. Thanks

**Comment by PeteCausey-Freeman** [comment]
Ok,

For acceptance

```json
{
  "metadata": {
    "seqrepo_db": "2018-08-21",
    "uta_schema": "uta_20180821",
    "variantvalidator_hgvs_version": "1.2.5.vv1",
    "variantvalidator_version": "1.0.4.dev116+g5a621f6.d20210105"
  },
  "status": "hello_world"
}
```

I kept the old status key to prevend @beboche 's stuff breaking. 

Note, the key seqrepo_db will have to change and also uta_schema will become vvta_schema, but you will get plenty of warning

**Comment by ifokkema** [comment]
Excellent!

> I kept the old status key to prevend @beboche 's stuff breaking.

I actually also have a method that tests for your `hello', so it also prevents my stuff from breaking :smile: 

Thanks!

**Comment by beboche** [comment]
> I actually also have a method that tests for your `hello', so it also prevents my stuff from breaking 😄

Exactly, let's avoid breaking anything!

**Comment by PeteCausey-Freeman** [comment]
Fantastic, all happy. I will push this up to both servers now then.

**Comment by PeteCausey-Freeman** [comment]
https://github.com/openvar/rest_variantValidator/commit/64d6d8a44bef2db949e17d93ddfd40b641d3481b
