### ISSUE TITLE
validation fails for NM_001287801.1 variants while this transcript is working in the webUI

### ISSUE THREAD

**Issue by beboche** [openvar/rest_variantValidator#81]
Hi Pete,

variants for transcript NM_001287801.1 return an Internal Server Error using the rest API, e.g.:

https://www608.lamp.le.ac.uk/VariantValidator/variantvalidator/GRCh38/NM_001287801.1%3Ac.1A%3ET/all?content-type=application%2Fjson

output:

```
{
  "message": "Internal Server Error"
}
```

In addition, using the web interface it is possible to validate the same variant NM_001287801.1:c.1A>T, except a minor verison warning linked to the accession version:

<img width="1153" alt="image" src="https://user-images.githubusercontent.com/29146185/203582898-ff221cf8-b627-4416-83e4-161531f6b7cd.png">
 
thanks

**Comment by Peter-J-Freeman** [comment]
Think this one is resolved @beboche?

**Comment by beboche** [comment]
absolutely
